### ISSUE TITLE
不支持本地图片的上传吗？

### ISSUE THREAD

**Issue by SenLief** [jxpeng98/obsidian-to-NotionNext#11]
试了一下无法上传本地图片，另外使用图床的markdown格式，也是无法上传上去的。

**Comment by jxpeng98** [comment]
是的，本地图片无法上传。obsidian到notion的转换使用到了[Martian](https://github.com/tryfabric/martian)。 这个插件只能支持url，所以暂时没有解决办法。 

图床的markdown我这边使用时没有问题的。 
在Obsidian显示：
<img width="431" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/0b920762-8f38-4243-a421-dc58a35b6363">

在notion显示：
<img width="797" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/21c417da-0269-462a-90c7-c6a47575ba98">

上边出现的字母路径，就是渲染失败的本地图片路径，下边是成功的图床。

**Comment by SenLief** [comment]
是的图床后面成功了，看来图片直接上传的希望是不大了，这个issue关闭了。
