### ISSUE TITLE
network error Error: Request failed, status 404

### ISSUE THREAD

**Issue by naxiaolu** [jxpeng98/obsidian-to-NotionNext#14]
您好，我遇到了问题，想请您帮忙看一下：
我现在单独在notion中可以同步到notionnext了。
然后我在插件中填写了必要的内容
![image](https://github.com/jxpeng98/obsidian-to-NotionNext/assets/151904996/92b772c1-c897-4a88-baeb-fc26316015c6)
然后我按照教程复制了一个内容如下
![image](https://github.com/jxpeng98/obsidian-to-NotionNext/assets/151904996/504985c8-2774-44f7-ba7f-3d165db5bdcc)
当我点击插件像让它同步的时候弹出network error Error: Request failed, status 404
请问怎么解决。

**Comment by jxpeng98** [comment]
我拿着模板尝试了一下，能够正常上传的。
<img width="708" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/b3b7c44d-f939-43c1-a107-05c76ced2523">
<img width="960" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/f13d08be-03a5-4c3c-91c9-735e38d1ba0d">


如果是出现了404的错误，一般来讲是notion的数据库没有匹配你的API。

你看看你的api是不是没有connect到数据库。在add connection里加上你的api再试一试。

<img width="575" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/d93d7441-9d1d-4c76-8331-ac1b2fe63ea4">

**Comment by naxiaolu** [comment]
按照您的方法成功了 果然是忘记add connection了，谢谢！
