### ISSUE TITLE
Custom database does not send URLs for File & Media properties and characters for Text properties

### ISSUE THREAD

**Issue by hatiwarechan** [jxpeng98/obsidian-to-NotionNext#15]
When I enter and submit property items to front matter in obsidian, the image URL I entered for the File & Media property and the text I entered for the Text property are not submitted and are empty.
On obsidian, both are set and entered as text properties. What are the possible causes?

![image](https://github.com/jxpeng98/obsidian-to-NotionNext/assets/123292993/5e895d8e-90c2-4a31-b974-66b825ac2c55)

**Comment by jxpeng98** [comment]
The bug has been fixed. You can update to the latest 2.2.3 version, and try again.

**Comment by hatiwarechan** [comment]
Resolved. Thank you very much!
