### ISSUE TITLE
slug和summary不写会报错？

### ISSUE THREAD

**Issue by sucooer** [jxpeng98/obsidian-to-NotionNext#19]
slug，summary 为必填项吗？我空着或者删除vercel部署都会报错。还有titleicon不能移除吗？生成的文章标题带个图标怪怪的
![](https://image.wooi.eu.org/file/399870a43c34de2e5f391.png)

**Comment by jxpeng98** [comment]
我把代码修改了一下，现在slug， summary， titleicon 都不是必选项了。 你可以安装最新的2.2.5的插件重新试一下。

**Comment by sucooer** [comment]
已经更新了，新版已不会报错。但不知道是文章内容太多还是什么原因，有些文章无法同步，纯文字或者内容少的就没问题，不知道作者有没有这个问题

**Comment by jxpeng98** [comment]
是的，太长就不能同步了，会返回400的错误。这个是notion API的限制，每一个block最多支持1000个字符。但是整体的长度好像没有影响。

你可以试试看把长的整的内容分成小块，比如代码块。
