### ISSUE TITLE
对于图床图片链接的识别问题

### ISSUE THREAD

**Issue by yoghurtlee-thu** [jxpeng98/obsidian-to-NotionNext#20]
如题。在文章中含有图床图片的链接的时候，在 Notion 中只留下了一个链接，没有嵌入图片。希望开发大佬能修复一下。

此外万分感谢大佬的这款宝藏插件解决了我的发布需求！Have a day as amazing as you are～

**Comment by jxpeng98** [comment]
你说的是图床的外链吗？这个渲染的话是没问题。

<img width="735" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/353d4ce6-a913-4a4a-9efb-c461a1bc0713">

<img width="604" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/806b3d2a-567b-4460-8766-e7ae3bba7e77">


但如果你想要的是Notion 网页bookmark的效果， 例如
<img width="575" alt="image" src="https://github.com/jxpeng98/obsidian-to-NotionNext/assets/83734772/86b8329d-5403-4e89-8013-10dd4e3ff21c">

这个暂时还弄不了。

如果方便的话，你再稍微详细说一下你的这个问题。

**Comment by yoghurtlee-thu** [comment]
> 我尝试复现了一下。
> 
> 这个应该是图片链接不规范导致的。 <img alt="image" width="565" src="https://private-user-images.githubusercontent.com/83734772/325957149-d1621bfd-df20-4753-9c9a-f7c1d7eea5ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNzgzMTAsIm5iZiI6MTcxNDE3ODAxMCwicGF0aCI6Ii84MzczNDc3Mi8zMjU5NTcxNDktZDE2MjFiZmQtZGYyMC00NzUzLTljOWEtZjdjMWQ3ZWVhNWVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDAwMzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhZGNlODc4MzU1MGY3M2NhMjNmYTMwNDkyOWE3MmEzODczNTFjNGNkYjA3OWJiZDU5NjQ0MzVhMGJjZDg0M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4R8KK8kcRTw8u42Lvi2ZBSoAdXedDuG6n8oZUVud4rY">
> 
> 在markdown文件转换过程中用到了[martian这个库](https://github.com/tryfabric/martian?tab=readme-ov-file#supported-markdown-elements)。 你可以看一些这个说明：图片链接必须要是规范可用的。
> 
> > Images 图片
> > ```
> > Inline images are extracted from the paragraph and added afterwards (as these are not supported in notion)
> > Image urls are validated, if they are not valid as per the Notion external spec, they will be inserted as text for you to fix manually
> > ```
> 
> 我之前的回答里有一个截图，你可以放在你的obsidian试一试
> 
> ```
> ![](https://minioapi.pjx.ac.cn/img1/2024/04/dea63c88b74d844e6780139b08ae5b4d.png)
> ```

应该是这样的，我的图片全都是 `.webp` 格式，那个库可能没办法将这个后缀识别为图片。感谢大佬。
