### ISSUE TITLE
Pluggin does not appear on Mac

### ISSUE THREAD

**Issue by JuliettePmt** [jxpeng98/obsidian-to-NotionNext#30]
Hello,

Thank you for your work, I really need such a pluggin. Unfortunately, the pluggin does not seem to appear on the left bar, were I should have an icon. 

I am on a MacOS 14.5 and Obsidian v1.6.7.

<img width="1084" alt="image" src="https://github.com/user-attachments/assets/4e20acdc-ae3e-4e4b-aa00-adf7b252a540">

Thank you !

**Comment by jxpeng98** [comment]
Hi, many thanks for using this plugin. 
I also use macOS. However, I did not have this problem. It is really strange. 

https://github.com/user-attachments/assets/980bbc5f-4fcc-4c7b-8db3-f7ec4d0e80b5

Once installed, it should be like this:
<img width="631" alt="image" src="https://github.com/user-attachments/assets/736813c8-b8c7-4310-a93e-b19eb3b55d6d">

May I know if you have the same problem when installing other community plugins, eg `Admonition`?

Could you switch on the restricted mode, try it again, and use `cmd+option+i` to check whether you have any errors in the developer console?

**Comment by JuliettePmt** [comment]
Thank you for your answer.

I do not seem to have any problem when downloading other pluggins, including Admonition.

Here are the logs when loading your pluggin :
<img width="545" alt="image" src="https://github.com/user-attachments/assets/87f81189-23bb-4b4f-bc84-5e55132d9da2">

**Comment by GiorCocc** [comment]
Plugin does not appear even on Windows

Details:
- Windows 11 (26120.1542)
- Obsidian (1.6.7)

![image](https://github.com/user-attachments/assets/0f912e8d-0f5d-4639-9d80-b149ce7e6869)

Problem: Missing Settings page to perform any kind of operation illustrated in the README.md file

**Comment by jxpeng98** [comment]
@JuliettePmt @GiorCocc 

Hi both,

Sorry for the long wait. I figured out it was caused by the Obsidian language setting.

@JuliettePmt May I know whether you use English-GB?


I will fix the bug and update a new version today.

**Comment by JuliettePmt** [comment]
Hi, 
Thank you for investing this problem. 
I use the French version of Obsidian.

**Comment by jxpeng98** [comment]
@JuliettePmt @GiorCocc 

Hi both, the latest version, `v2.4.2`, has been published. Please feel free to have a try. If you still have any problems, please let me know.

**Comment by JuliettePmt** [comment]
Thank you very much, it does work !

I just have a last question : do you intend to implement a function to save files the other way around, from Notion to Obsidian ? Or even an auto-sync function, that would automatically transmit modifications from one app to the other ? This would make my life SO MUCH easier.

Thank you :)

**Comment by jxpeng98** [comment]
> Thank you very much, it does work !
> 
> 
> 
> I just have a last question : do you intend to implement a function to save files the other way around, from Notion to Obsidian ? Or even an auto-sync function, that would automatically transmit modifications from one app to the other ? This would make my life SO MUCH easier.
> 
> 
> 
> Thank you :)

@JuliettePmt 
I want to make sure I understand correctly. You want to write notes in Obsidian and sync them to Notion. However, you also make changes to the Notion notes, and you want those changes to sync back to the linked Obsidian note. Is that right?

You mentioned “automatically”. May I know how you would like to trigger the syncing process?

**Comment by JuliettePmt** [comment]
Hello, 

Here is the process I currently follow : 
I use Notion to take notes on books and articles I read for my PhD. Everything in stocked in a database. I use Notion because of its user friendly interface + database system + backups.
However, I find the canvas function of Obsidian to be really useful, so I regularly export all of my Notion notes into Obsidian (filtering new notes from old ones with a little Python script).

What I basically need would be to have one and unique file for each book/article read, shared on both apps. Since I take my notes into Notion, a plugin that would sync Notion notes into Obsidian (so the reverse of what your plugin is currently doing) would be a great start. It does not have to be automatic, but I guess the ideal scenario would be that a change in a file would trigger a sync in both apps.

I hope I make sense, thank you for taking time

**Comment by jxpeng98** [comment]
@JuliettePmt 

Thanks for your explanation. I understand the process. 

I will integrate some services with this plugin to support your requests. However, I do not have an estimated date for publishing the version.
