### ISSUE TITLE
latex 多了换行符\\

### ISSUE THREAD

**Issue by codebysandwich** [jxpeng98/obsidian-to-NotionNext#31]
obsidian中latex公式：
$$
\textbf{A}=\left[\begin{matrix}
a_{11} & a_{12} & \cdots & a_{1k} \\
a_{21} & a_{22} & \cdots & a_{2k} \\
\vdots & \vdots & \ddots & \vdots \\
a_{n1} & a_{n2} & \cdots & a_{nk} \\
\end{matrix}\right],
\textbf{B}=\left[\begin{matrix}
b_{11} & b_{12} & \cdots & b_{1m} \\
b_{21} & b_{22} & \cdots & b_{2m} \\
\vdots & \vdots & \ddots & \vdots \\
b_{k1} & b_{k2} & \cdots & b_{km} \\
\end{matrix}\right]
$$

导入notion后：
\textbf{A}=\left[\begin{matrix}\\
a_{11} & a_{12} & \cdots & a_{1k} \\\\
a_{21} & a_{22} & \cdots & a_{2k} \\\\
\vdots & \vdots & \ddots & \vdots \\\\
a_{n1} & a_{n2} & \cdots & a_{nk} \\\\
\end{matrix}\right],\\
\textbf{B}=\left[\begin{matrix}\\
b_{11} & b_{12} & \cdots & b_{1m} \\\\
b_{21} & b_{22} & \cdots & b_{2m} \\\\
\vdots & \vdots & \ddots & \vdots \\\\
b_{k1} & b_{k2} & \cdots & b_{km} \\\\
\end{matrix}\right]

每一行都多了\\换行符，可以选择不加么？

**Comment by jxpeng98** [comment]
latex 的默认换行符是`\\`。
如果我把你上边的单换行符的代码打到obsidian，显示效果是这样的
<img width="730" alt="image" src="https://github.com/user-attachments/assets/41312639-ea49-4e91-820a-bee1e57459f0">

如果是用转换后的notion的代码，显示效果就是正常的矩阵
<img width="713" alt="image" src="https://github.com/user-attachments/assets/3b701dd3-f666-4fca-856e-76e1682c248f">

在overleaf上，他们给的换行符说明也是以下三种：
>There are three commands here that work the same in the example:
>    \\ (two backslashes)
>    \newline
>    \hfill \break


想问一下，下边这种是你想要的效果吗？

**Comment by codebysandwich** [comment]
谢谢解答，我没有检查纯文本和github渲染差异（\预览转义了，所以...您这边看到的单换行符，其实我的文本是双\），我原本的意思是每一行都多了两个反斜杠换行符，我文本图截图您看下
<img width="683" alt="image" src="https://github.com/user-attachments/assets/5995e1d9-7a3b-41d2-ba20-827d07666a5e">

**Comment by jxpeng98** [comment]
我更新了一下，现在不会加换行符了。
你可以更新一下最新的版本`2.3.5`试一下。
<img width="530" alt="image" src="https://github.com/user-attachments/assets/3369db42-d749-402a-b426-eb80a8055676">

<img width="516" alt="image" src="https://github.com/user-attachments/assets/68f30833-c346-4c78-92fc-a82e71babce7">

<img width="489" alt="image" src="https://github.com/user-attachments/assets/de26b043-ee67-4f7d-943b-b6c3f4db1982">

<img width="485" alt="image" src="https://github.com/user-attachments/assets/2036fd7f-7007-44f4-9463-9415aece00b6">

**Comment by codebysandwich** [comment]
您好，多谢更新，测试了下目前没有发现问题😀
