### ISSUE TITLE
Error message: tags is expected to be relation. Even though the notion database has tags in relation!

### ISSUE THREAD

**Issue by pratyushV-l** [jxpeng98/obsidian-to-NotionNext#38]
Hi! I am reporting an issue when trying out the plugin for the first time. When I try to publish a note to notion, with both the title and tags metadata correctly filled in, and the notion database having the right naming and types, I still get the error - Error message: 
 tags is expected to be relation. Please help me in fixing this, I have attached some resources below to better understand the problem.

Notion Database- https://right-venom-936.notion.site/11b3b6338f47818eabafe4d59c782738?v=11b3b6338f47816e8a81000cb4944a17
Obsidian - 
![image](https://github.com/user-attachments/assets/c9966d72-d583-4908-9b61-3787ccf28444)

**Comment by jxpeng98** [comment]
@pratyushV-l 
Thanks for using the plugin. 

You set the wrong property for `tags`.

In your Notion dataset, you set `tags` as the relation.
<img width="228" alt="image" src="https://github.com/user-attachments/assets/f869908d-8d10-45cc-98a0-325d4707565b">

You should set it as the `multi-select`.
<img width="375" alt="image" src="https://github.com/user-attachments/assets/c8928619-d97c-444f-8aa4-2e15a2e68199">

**Comment by pratyushV-l** [comment]
Thank You, I have bypassed the issue now. I am facing another issue with the error:
`plugin:share-to-notionnext:21712 Uncaught (in promise) FetchError: request to https://api.notion.com/v1/pages failed, reason: write ECONNABORTED
    at ClientRequest.eval (plugin:share-to-notionnext:21712:16)
    at ClientRequest.emit (node:events:529:35)
    at TLSSocket.socketErrorListener (node:_http_client:501:9)
    at TLSSocket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`
Please let me know how to resolve this, and also let me know if needed to open this as a seperate issue

**Comment by pratyushV-l** [comment]
Nevermind, this issue was explicitly only for that individual note, it works otherwise. Thank You!
