### ISSUE TITLE
关于Title字段与发布后名称的问题

### ISSUE THREAD

**Issue by ycbrd** [jxpeng98/obsidian-to-NotionNext#41]
作者您好，感谢您提供的插件，很好地满足了我的需要，也感谢您回复用户提出的issue.

我使用自定义数据库的设置。插件要求在发布MD文件时，yaml中的title字段名可以自定义，但要和设置中、Notion中保持一致。我注意到发布后的Notion页面名称和MD文档的名称一致，但不一定和所设置的字段取值一致。无论这个字段值我怎么填，Notion页面名称总是和MD文档的名称一样。这是本来的设计如此，还是我使用遇到了问题？如果页面名称取字段值而不是文件名，就可以允许页面在Obsidian和Notion中取不同的名称（当然也可相同），提供了更大自由度。
<img width="421" alt="image" src="https://github.com/user-attachments/assets/ab666664-2d92-44a8-8b78-45efd1a5d99b">

因为Notion页面按文件名命名，因此甚至没有这个title字段的MD文档，也能正常发布，只是ob会抛出一个标签错误（但我没有自定义标签字段）：
![image](https://github.com/user-attachments/assets/f5c57083-19ec-4266-87c6-7a177a96d9cb)
但是在这种情况下，Notion中的相应页面，标题是空的。所以我猜想这可能是是一个bug。

**Comment by jxpeng98** [comment]
你好，感谢使用。

能否问一下你用的是哪一个数据库的设置？一般数据库还是自定义？

**Comment by ycbrd** [comment]
> 能否问一下你用的是哪一个数据库的设置？一般数据库还是自定义？

您好。使用的是自定义设置。

**Comment by jxpeng98** [comment]
> > 能否问一下你用的是哪一个数据库的设置？一般数据库还是自定义？
> 
> 您好。使用的是自定义设置。

@ycbrd 

修复了，我在我这边测试没问题。 你更新`v2.4.3`试一下。如果还有问题就留言告诉我。

**Comment by ycbrd** [comment]
谢谢您，我这边测试也没问题。感谢您的回复和高效处理。
