### ISSUE TITLE
发布失败

### ISSUE THREAD

**Issue by moerjie** [jxpeng98/obsidian-to-NotionNext#47]
我写了一个博客，顺利同步到了notion，后面我更新了以后就无法同步过去了，而且会报 validation 400，但是新建一个文件后仍然可以同步，报错如下：
Error message: 
 Content creation Failed. Fix the following: 
Number of cells in table row must match the table width of the parent table
Number of cells in table row must match the table width of the parent table
﻿

**Comment by moerjie** [comment]
是因为我第二次上传的时候把之前生成的notion 的id删掉了吗😂

**Comment by jxpeng98** [comment]
现在的同步策略就是找表头有没有生成的notion id。 如果有，就删除原来的notion页面，然后重新生成一个新的并且在鼻癌头更新notion id。 如果没有notion id， 直接创建一个新的页面。

但如果obsidian里表头有id，但是notion里已经删除了。这个就会返回400错误。

根据你的反馈，你这个好像是因为markdown表格的结构错误导致的，并不是因为表头的问题？
