### ISSUE TITLE
无法在社区市场正常添加插件

### ISSUE THREAD

**Issue by 2019YKL** [jxpeng98/obsidian-to-NotionNext#8]
非常感谢您设计这款插件，但是不知什么原因，我目前暂时没办法从社区市场安装这个插件。

应该不是我个人网络问题引起的，其他插件测试安装正常，沙盒模式下测试问题可复现。

如果需要我提供更详细的信息，请您告诉我~

![screenshots](https://github.com/jxpeng98/obsidian-to-NotionNext/assets/51532948/fd025a3f-5f5f-4243-93f4-879395a38591)

**Comment by jxpeng98** [comment]
bug修复了，可以正常安装了。

**Comment by 2019YKL** [comment]
> bug修复了，可以正常安装了。

非常感谢您修复Bug~ 已使用上了，谢谢！
